version: "3.8"

services:
  postgres:
    container_name: movie_db
    image: postgres
    restart: always
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  go:
    container_name: movie_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - "postgres"
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: